spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_storage?connectTimeout=5000&socketTimeout=60000
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver


  flyway:
    schemas: cloud_storage
    baseline-on-migrate: true

  jpa:
    show-sql: true

  sql:
    init:
      mode: always
      continue-on-error: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

security:
  jwt:
    secret: 2A462D4A614E645267556B58703273357638792F423F4428472B4B6250655368
    access: 3600000
    refresh: 2592000000
